import * as fs from "fs/promises";
import {type PadEditor} from "@localbytes/localdeck-components/src/utils/PadCfg";
import {getEditorUrl} from "@localbytes/localdeck-components/src/utils/utils";
import ConfigUtil from "@localbytes/localdeck-components/src/utils/config-util";
import {type DeepPartial} from "@localbytes/localdeck-components/src/utils/types";
import {ConfiguredButton} from "@localbytes/localdeck-codegen/lib/virtuals/configured-button";
import newConfig from "@localbytes/localdeck-codegen/lib/esphome-localdeck";

export default defineEventHandler(async (event) => {
    const {filesDir} = useRuntimeConfig();
    const {filename} = getQuery(event)
    const body = await readBody(event) satisfies { editor: DeepPartial<PadEditor> };

    const configUtil = new ConfigUtil();
    configUtil.setChanges(body.editor);

    const editor: PadEditor = configUtil.editor();

    if (!editor) {
        throw createError({
            statusCode: 400,
            statusMessage: "No editor found",
        });
    }

    const path = `${filesDir}/${filename}`;

    let fileContent = "";
    try {
        const search = "changes will be lost!";
        const content = await fs.readFile(path, "utf8");
        let pos = content.indexOf(search);
        if (pos > 0) {
            fileContent = content.substring(0, pos + search.length);
        }
    } catch (e) {
        // ignore
    }

    if (fileContent === "") {
        fileContent += "# This file was generated by the LocalBytes LocalDeck Configurator\n"

        fileContent += newConfig({
            withDefaults: true,
            stopBeforeCustom: true
        }).config.synthYaml();

        fileContent += "\n# Anything below this line will be removed when saving.\n"
        fileContent += "# To change this, navigate to the LocalBytes LocalDeck Configurator.\n"
        fileContent += "# Your changes will be lost!"
    }

    fileContent += `\n# Edit: ${getEditorUrl(configUtil.getChanges())}\n\n`

    let {config} = newConfig({withDefaults: false});
    Object.entries(editor.buttons).forEach(([num, b]) => config.addComponent(new ConfiguredButton(b)));
    fileContent += config.synthYaml();

    await fs.writeFile(path, fileContent, "utf8");
    return {filename, path}
});
