import * as fs from "fs/promises";
import newConfig from "@localbytes/localdeck-codegen/lib/esphome-localdeck";
import {type PadEditor} from "~/lib/PadCfg";
import {getEditorUrl} from "~/lib/utils";
import {ConfiguredButton} from "@localbytes/localdeck-codegen/lib/virtuals/configured-button";
import ConfigUtil from "~/lib/config-util";
import {DeepPartial} from "~/lib/types";

export default defineEventHandler(async (event) => {
    const {filesDir} = useRuntimeConfig();
    const {filename} = getQuery(event)
    const body = await readBody(event) satisfies { editor: DeepPartial<PadEditor> };

    const configUtil = new ConfigUtil();
    configUtil.setChanges(body.editor);

    const editor: PadEditor = configUtil.editor();

    if (!editor) {
        throw createError({
            statusCode: 400,
            statusMessage: "No editor found",
        });
    }

    const path = `${filesDir}/${filename}`;

    let filecontent = "";
    try {
        const search = "changes will be lost!";
        const content = await fs.readFile(path, "utf8");
        let pos = content.indexOf(search);
        if (pos > 0) {
            filecontent = content.substring(0, pos + search.length);
        }
    } catch (e) {
        // ignore
    }

    if (filecontent === "") {
        filecontent += "# This file was generated by the LocalBytes LocalDeck Configurator\n"

        filecontent += newConfig({
            withDefaults: true,
            stopBeforeCustom: true
        }).config.synthYaml();

        filecontent += "\n# Anything below this line will be removed when saving.\n"
        filecontent += "# To change this, navigate to the LocalBytes LocalDeck Configurator.\n"
        filecontent += "# Your changes will be lost!"
    }

    filecontent += `\n# Edit: ${getEditorUrl(configUtil.getChanges())}\n\n`

    let {config} = newConfig({withDefaults: false});
    Object.entries(editor.buttons).forEach(([num, b]) => config.addComponent(new ConfiguredButton(b)));
    filecontent += config.synthYaml();

    await fs.writeFile(path, filecontent, "utf8");
    return {filename, path}
});
