packages:
  - packages/*
  - components/**
  - '!**/test/**'

catalog:
  '@nuxt/test-utils': ^3.23.0
  nuxt: ^4.3.0
  typescript: ^5.9.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - unrs-resolver
  - vue-demi
