packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

catalog:
  typescript: ^5.5.4
  nuxt: ^3.13.2
  "@nuxt/test-utils": 3.14.4

