packages:
  - packages/*
  - components/**
  - '!**/test/**'

catalog:
  '@nuxt/test-utils': 3.14.4
  nuxt: ^3.13.2
  typescript: ^5.5.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msw
  - vue-demi
