packages:
  - packages/*
  - components/**
  - '!**/test/**'

catalog:
  nuxt: ^4.5.2
  typescript: ^6.0.3
  vite: ^8.3.0
  vitest: ^5.0.1

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  esphome-config-ts@git+https://github.com/LocalBytes/esphome-config-ts.git: true
  unrs-resolver: true
