substitutions:
  name: localdeck-test
  friendly_name: LocalDeck TEST
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
  on_boot:
    - light.turn_on:
        id: ledstrip
        brightness: 25%
        effect: Addressable Rainbow
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options: { }
light:
  - platform: esp32_rmt_led_strip
    name: Ledstrip
    id: ledstrip
    rgb_order: GRB
    pin: GPIO8
    rmt_channel: 0
    num_leds: 24
    chipset: SK6812
    restore_mode: RESTORE_AND_OFF
    effects:
      - addressable_rainbow:
          name: Addressable Rainbow

