on:
  push:
    branches:
      - main
  pull_request:


name: "Test"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js & Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm install -r
          pnpx playwright install --with-deps

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
